### ISSUE TITLE
Backoffice doesn't load if lastEnv's Kuzzle isn't up

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-backoffice#343] opened 2017-07-04 14:05 UTC
I have 4 envs configured in my localStorage.

lastEnv's Kuzzle was down => Kuzzle BO doesn't start. I had to clean up my LocalStorage, and reconfigure the envs.

**Comment by AnthonySendra** [comment] 2017-07-10 08:39
Duplicate of https://github.com/kuzzleio/kuzzle-backoffice/issues/329
Fixed by https://github.com/kuzzleio/kuzzle-backoffice/pull/339

**Closed by AnthonySendra** 2017-07-10 08:39 UTC
