### ISSUE TITLE
Unable to see the newly created document in list

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#192] opened 2017-01-11 10:44 UTC
Since the UI does not wait the 1s indexation delay in ES, the user cannot see a document in the list right after creating it (refreshing the page is necessary).

**Comment by AnthonySendra** [comment] 2017-01-11 14:28
Hi @xbill82,
I have tried and can't reproduce. Could you double check please?

**Comment by xbill82** [comment] 2017-01-11 14:49
yep it happens very very rarely. I had it once (then raised the issue) but never got it again. Should not be prioritary.

**Comment by AnthonySendra** [comment] 2017-01-19 10:46
Fixed with `{refresh: 'wait_for'}`

**Closed by AnthonySendra** 2017-01-19 10:46 UTC
Labels: bug
